 package ecommerce.main;
import java.util.List;

import ecommerce.com.Product;
import ecommerce.com.businesslogic.Service;
public class Main {
	public static void main(String args[]) {
		
		//id automatically generated by hibernate engine
		
		Service serve = new Service();
		
//ADDING PRODUCTS
		
		Product newproducts=new Product();
	    newproducts.setLaptopname("DELL");
		newproducts.setColor("silver");
	    newproducts.setModel("Inspiron");
		newproducts.setScreensize("15 inches");
		newproducts.setWeight("1.5 Kg");
		
	    
//UPDATE PRODUCTS
		
		//Product updateproduct= new Product();
		//updateproduct.setLaptopname("ASUS");
		//updateproduct.setColor("Black");
		//updateproduct.setModel("X515JA-EJ362WS");
		//updateproduct.setScreensize("18inches");
		//updateproduct.setWeight("1.6kgs");
		//Product updated=serve.updateProductById(updateproduct, 8);
		//String laptopName=updated.getLaptopname();
		//System.out.println("Updated LaptopName is: " + laptopName);
		
		
//LLIST OF ALL PRODUCTS
		
         //List<Product> listOfProducts= serve.getListOfAllProducts();
	     //for(Product products:listOfProducts) {
		 //System.out.println(laptopName);
		// System.out.println("screensize is: " + newlist.getScreensize());
		// System.out.println("laptopName is: " + newlist.getLaptopname());
		// System.out.println("model is: " + newlist.getModel());

       	 //	}
	     // System.out.println("Done");
	    		
		
//DELETE PRODUCTS BY ID
		
	    		//Product gotid =serve.findProductById(3);
	    		//gotid.getId();
	    		//System.out.println("is.."+gotid.getId());
	    		//serve.deleteProductRecordById(3);
	 
		
//GET PRODUCTS DETAILS BY ID
		
	    		//Product prod = serve.getProductDetailsById(2);
	    		//System.out.println("laptopName is: " + prod.getLaptopname());
	    		//System.out.println("Color is: " + prod.getColor());
	    		//System.out.println("Model is: " + prod.getModel());
	    	
//DELETING ALL PRODUCTS	
	    		
	    		//String result = serve.deleteAllProductRecord();
	    		//System.out.println(result);
	    		
	    	}

	    
		
	}

